baseURL = "https://www.mikeraynham.co.uk"
languageCode = "en-gb"
title = "Mike Raynham"
theme = "beautifulhugo"

[Params]

[Author]
  name = "Mike Raynham"
  github = "mikeraynham"
  linkedin = "mike-raynham-18995294"
  stackoverflow = "/users/340355/mike"

